id: I6355BFBC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:17:09+00:00'
last_modified: '2022-06-08T06:53:04.586149+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC35
  title: གཏན་བདེའི་གཞི་མ་སྲིད་པའི་རྒྱུད་རིམ་ལ་བརྟག་པ་སྟེ་ལེགས་གནས་ཀུན་འདུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    7C66:
      image_group_id: I2PD18382
      title: ''
      total_pages: 246
      order: 1
      base_file: 7C66.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
